--DROP TABLE PERSON
--DROP TABLE ADDRESS
--DROP TABLE CONTACT

CREATE TABLE PERSON
(
	PERSON_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	FIRSTNAME VARCHAR(50) NOT NULL,
	LASTNAME VARCHAR(50) NOT NULL,
	DATEOFBIRTH DATETIME NOT NULL
)


INSERT INTO [dbo].[PERSON] ( [LASTNAME], [FIRSTNAME], [DATEOFBIRTH]) 
VALUES ( N'Anthony', N'Di Persio', N'1990-06-20 00:00:00'),
	   ( N'Ihab', N'Abadi', N'1987-09-11 00:00:00'),
	   ( N'Marine', N'Abadi', N'1992-05-16 00:00:00')

CREATE TABLE ADDRESS
(
	ADDRESS_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NUMBER INT NOT NULL,
	ROAD_NAME VARCHAR(50) NOT NULL,
	ZIP_CODE INT NOT NULL,
	CITY VARCHAR(50) NOT NULL,
	COUNTRY VARCHAR(50) NOT NULL,
)


INSERT INTO [dbo].[ADDRESS] ( [NUMBER], [ROAD_NAME], [ZIP_CODE], [CITY], [COUNTRY]) 
VALUES ( 170, N'rue de la République', 59800, N'Lille', N'France'),
	   ( 2, N'rue des Tilleuls', 59599, N'Tourcoing', N'France'),
	   ( 2, N'rue des Tilleuls', 59599, N'Tourcoing', N'France')

CREATE TABLE CONTACT
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	EMAIL VARCHAR(50) NOT NULL,
	PHONE VARCHAR(50) NOT NULL,
	PERSON_ID INT NOT NULL,
	ADDRESS_ID INT NOT NULL,
)


INSERT INTO [dbo].[CONTACT] ( [EMAIL], [PHONE], [PERSON_ID], [ADDRESS_ID])
VALUES ( N'anthony@utopios.net', N'+33 6 41 52 63 98', 1, 1),
	   ( N'Ihab@utopios.net', N'+33 6 58 74 12 36', 2, 2),
	   ( N'marine@utopios.net', N'+33 6 41 02 10 02', 3, 3)