--INSERT INTO ADDRESS (NUMBER,ROAD_NAME,ZIP_CODE,CITY,COUNTRY) OUTPUT INSERTED.ADDRESS_ID VALUES (5,'Rue de Paris',59800,'Lille','France')

--UPDATE ADDRESS SET NUMBER=1,ROAD_NAME='rue de la Liberté',ZIP_CODE=598001,CITY='Lilles',COUNTRY='Francia' WHERE ADDRESS_Id = 1006

SELECT ADDRESS_ID, NUMBER, ROAD_NAME, ZIP_CODE, CITY, COUNTRY FROM ADDRESS WHERE ADDRESS_ID = 1008