DROP TABLE person

CREATE TABLE [dbo].[PERSON] (
    [ID]       INT  IDENTITY(1,1) NOT NULL,
    [NOM]      VARCHAR (50) NOT NULL,
    [EMAIL]    VARCHAR (50) NOT NULL,
    [TELEPHONE] VARCHAR (17) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);
