DROP TABLE CLIENT, OPERATION, COMPTE

CREATE TABLE CLIENT
(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NOM VARCHAR(50) NOT NULL,
	PRENOM VARCHAR(50) NOT NULL,
	TELEPHONE VARCHAR(17) NOT NULL,
)



CREATE TABLE OPERATION
(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	MONTANT DECIMAL(10,2) NOT NULL,
	DATOPERATION DATETIME NOT NULL,
	COMPTE_ID INT NOT NULL,
)

CREATE TABLE COMPTE
(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CLIENT_ID INT NOT NULL,
	SOLDE DECIMAL(10,2) NOT NULL,
	TAUX DECIMAL(10,2) NOT NULL,
	COUT DECIMAL(10,2) NOT NULL,
)




